songs = [
    {'mood': '설렘', 'genre': '댄스', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '인디팝', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '발라드', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '록', 'title': 'Polaroid Love', 'artist': 'ENHYPEN', 'youtube': 'https://youtu.be/HGt-I6_hDk4', 'image': 'https://i.ytimg.com/vi/HGt-I6_hDk4/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '힙합', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '설렘', 'genre': 'R&B', 'title': 'Spring Day', 'artist': 'BTS', 'youtube': 'https://youtu.be/xEeFrLSkMm8', 'image': 'https://i.ytimg.com/vi/xEeFrLSkMm8/hqdefault.jpg'},
    {'mood': '설렘', 'genre': 'EDM', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '시티팝', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '어쿠스틱', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '라틴팝', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '설렘', 'genre': '팝', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '댄스', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '인디팝', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '발라드', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '록', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '힙합', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': 'R&B', 'title': 'Hype Boy', 'artist': 'NewJeans', 'youtube': 'https://youtu.be/js1CtxSY38I', 'image': 'https://i.ytimg.com/vi/js1CtxSY38I/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': 'EDM', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '시티팝', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '어쿠스틱', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '라틴팝', 'title': 'Polaroid Love', 'artist': 'ENHYPEN', 'youtube': 'https://youtu.be/HGt-I6_hDk4', 'image': 'https://i.ytimg.com/vi/HGt-I6_hDk4/hqdefault.jpg'},
    {'mood': '쓸쓸함', 'genre': '팝', 'title': 'Polaroid Love', 'artist': 'ENHYPEN', 'youtube': 'https://youtu.be/HGt-I6_hDk4', 'image': 'https://i.ytimg.com/vi/HGt-I6_hDk4/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '댄스', 'title': 'Spring Day', 'artist': 'BTS', 'youtube': 'https://youtu.be/xEeFrLSkMm8', 'image': 'https://i.ytimg.com/vi/xEeFrLSkMm8/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '인디팝', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '발라드', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '록', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '힙합', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '자신감', 'genre': 'R&B', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '자신감', 'genre': 'EDM', 'title': 'Spring Day', 'artist': 'BTS', 'youtube': 'https://youtu.be/xEeFrLSkMm8', 'image': 'https://i.ytimg.com/vi/xEeFrLSkMm8/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '시티팝', 'title': 'Spring Day', 'artist': 'BTS', 'youtube': 'https://youtu.be/xEeFrLSkMm8', 'image': 'https://i.ytimg.com/vi/xEeFrLSkMm8/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '어쿠스틱', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '라틴팝', 'title': 'Hype Boy', 'artist': 'NewJeans', 'youtube': 'https://youtu.be/js1CtxSY38I', 'image': 'https://i.ytimg.com/vi/js1CtxSY38I/hqdefault.jpg'},
    {'mood': '자신감', 'genre': '팝', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '댄스', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '인디팝', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '발라드', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '록', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '힙합', 'title': 'Polaroid Love', 'artist': 'ENHYPEN', 'youtube': 'https://youtu.be/HGt-I6_hDk4', 'image': 'https://i.ytimg.com/vi/HGt-I6_hDk4/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': 'R&B', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': 'EDM', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '시티팝', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '어쿠스틱', 'title': 'Spring Day', 'artist': 'BTS', 'youtube': 'https://youtu.be/xEeFrLSkMm8', 'image': 'https://i.ytimg.com/vi/xEeFrLSkMm8/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '라틴팝', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '기분전환', 'genre': '팝', 'title': 'Hype Boy', 'artist': 'NewJeans', 'youtube': 'https://youtu.be/js1CtxSY38I', 'image': 'https://i.ytimg.com/vi/js1CtxSY38I/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '댄스', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '인디팝', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '발라드', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '록', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '힙합', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '우울함', 'genre': 'R&B', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '우울함', 'genre': 'EDM', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '시티팝', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '어쿠스틱', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '라틴팝', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '우울함', 'genre': '팝', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '신남', 'genre': '댄스', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '신남', 'genre': '인디팝', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '신남', 'genre': '발라드', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '신남', 'genre': '록', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '신남', 'genre': '힙합', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '신남', 'genre': 'R&B', 'title': 'Hype Boy', 'artist': 'NewJeans', 'youtube': 'https://youtu.be/js1CtxSY38I', 'image': 'https://i.ytimg.com/vi/js1CtxSY38I/hqdefault.jpg'},
    {'mood': '신남', 'genre': 'EDM', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '신남', 'genre': '시티팝', 'title': 'Hype Boy', 'artist': 'NewJeans', 'youtube': 'https://youtu.be/js1CtxSY38I', 'image': 'https://i.ytimg.com/vi/js1CtxSY38I/hqdefault.jpg'},
    {'mood': '신남', 'genre': '어쿠스틱', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '신남', 'genre': '라틴팝', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '신남', 'genre': '팝', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '댄스', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '인디팝', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '발라드', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '록', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '힙합', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '힐링', 'genre': 'R&B', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '힐링', 'genre': 'EDM', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '시티팝', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '어쿠스틱', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '라틴팝', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '힐링', 'genre': '팝', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '댄스', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '인디팝', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '발라드', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '록', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '힙합', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': 'R&B', 'title': 'LOVE SCENARIO', 'artist': 'iKON', 'youtube': 'https://youtu.be/vecSVX1QYbQ', 'image': 'https://i.ytimg.com/vi/vecSVX1QYbQ/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': 'EDM', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '시티팝', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '어쿠스틱', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '라틴팝', 'title': 'Polaroid Love', 'artist': 'ENHYPEN', 'youtube': 'https://youtu.be/HGt-I6_hDk4', 'image': 'https://i.ytimg.com/vi/HGt-I6_hDk4/hqdefault.jpg'},
    {'mood': '위로받고 싶음', 'genre': '팝', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '댄스', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '인디팝', 'title': 'Polaroid Love', 'artist': 'ENHYPEN', 'youtube': 'https://youtu.be/HGt-I6_hDk4', 'image': 'https://i.ytimg.com/vi/HGt-I6_hDk4/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '발라드', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '록', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '힙합', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': 'R&B', 'title': 'Hype Boy', 'artist': 'NewJeans', 'youtube': 'https://youtu.be/js1CtxSY38I', 'image': 'https://i.ytimg.com/vi/js1CtxSY38I/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': 'EDM', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '시티팝', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '어쿠스틱', 'title': 'Spring Day', 'artist': 'BTS', 'youtube': 'https://youtu.be/xEeFrLSkMm8', 'image': 'https://i.ytimg.com/vi/xEeFrLSkMm8/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '라틴팝', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '비 오는 날', 'genre': '팝', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '댄스', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '인디팝', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '발라드', 'title': 'Polaroid Love', 'artist': 'ENHYPEN', 'youtube': 'https://youtu.be/HGt-I6_hDk4', 'image': 'https://i.ytimg.com/vi/HGt-I6_hDk4/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '록', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '힙합', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': 'R&B', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': 'EDM', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '시티팝', 'title': 'Hype Boy', 'artist': 'NewJeans', 'youtube': 'https://youtu.be/js1CtxSY38I', 'image': 'https://i.ytimg.com/vi/js1CtxSY38I/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '어쿠스틱', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '라틴팝', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '친구들과 함께', 'genre': '팝', 'title': 'Magnetic', 'artist': 'ILLIT', 'youtube': 'https://youtu.be/Vk5-c_v4gMU', 'image': 'https://i.ytimg.com/vi/Vk5-c_v4gMU/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '댄스', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '인디팝', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '발라드', 'title': 'Love Dive', 'artist': 'IVE', 'youtube': 'https://youtu.be/Y8JFxS1HlDo', 'image': 'https://i.ytimg.com/vi/Y8JFxS1HlDo/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '록', 'title': 'Love Shot', 'artist': 'EXO', 'youtube': 'https://youtu.be/pSudEWBAYRE', 'image': 'https://i.ytimg.com/vi/pSudEWBAYRE/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '힙합', 'title': 'Blue Hour', 'artist': 'TXT', 'youtube': 'https://youtu.be/Vd9QkWsd5p4', 'image': 'https://i.ytimg.com/vi/Vd9QkWsd5p4/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': 'R&B', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': 'EDM', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '시티팝', 'title': 'Red Flavor', 'artist': 'Red Velvet', 'youtube': 'https://youtu.be/WyiIGEHQP8o', 'image': 'https://i.ytimg.com/vi/WyiIGEHQP8o/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '어쿠스틱', 'title': 'Feel Special', 'artist': 'TWICE', 'youtube': 'https://youtu.be/3ymwOvzhwHs', 'image': 'https://i.ytimg.com/vi/3ymwOvzhwHs/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '라틴팝', 'title': 'Spring Day', 'artist': 'BTS', 'youtube': 'https://youtu.be/xEeFrLSkMm8', 'image': 'https://i.ytimg.com/vi/xEeFrLSkMm8/hqdefault.jpg'},
    {'mood': '추억에 잠기고 싶을 때', 'genre': '팝', 'title': 'Cupid', 'artist': 'FIFTY FIFTY', 'youtube': 'https://youtu.be/6uvUTz0uP3k', 'image': 'https://i.ytimg.com/vi/6uvUTz0uP3k/hqdefault.jpg'},
] 

# ... 이어지는 전체 곡 리스트는 필요에 따라 계속 추가 가능
]
